### ISSUE TITLE
Sample code is missing

### ISSUE THREAD

**Issue by evgeniyd** [casademora/CoreHTTP#1]
There is no sample code which would show-case the usage of the library. It could be in the same repo or in some other one (with a link in this repo's README.md)

**Comment by casademora** [comment]
Yeah, I'm aware of that. I've been trying this out with another, separate, project to make sure everything works.

**Comment by casademora** [comment]
I added a Sample project (d5a57ae0dc74d944bbe0e1160d720e4606992303). Give it a look. It requires that you sign up for a free API key from the NASA api. More information about that here: https://api.nasa.gov/api.html#authentication
